### ISSUE TITLE
Cannot use Priority Classes

### ISSUE THREAD

**Issue by wilson-duan** [armadaproject/armada-operator#307]
I have a cluster with Armada installed through the kind installation, and submitting jobs that use non-default priority classes to Armada causes this error:

`Error: error submitting request &api.JobSubmitRequest{Queue:"queue-a", JobSetId:"job-set-1", JobRequestItems:[]*api.JobSubmitRequestItem{(*api.JobSubmitRequestItem)(0xc000636280)}}: rpc error: code = InvalidArgument desc = priority class armada-high is not supported`

The priority class armada-high is given by this yaml file (note that it is equivalent to the setup of the default armada priority class, but with a different name and priority value):

```
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: armada-high
value: 1000001
globalDefault: false
description: "Higher priority than armada-default."
```

According to the documentation, "job priority classes are set by setting the priorityClassName field of the podspec embedded in the job", which is what I did:

```
queue: queue-a
jobSetId: job-set-1
jobs:
  - namespace: default
    priority: 1
    podSpec:
      priorityClassName: armada-high
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
        - name: sleeper-high
          image: alpine:latest
          command:
            - sh
          args:
            - -c
            - sleep 300
          resources:
            limits:
              memory: 128Mi
              cpu: 0.5
            requests:
              memory: 128Mi
              cpu: 0.5
```

**Comment by dejanzele** [comment]
Hi @wilson-duan,

Armada Server supports configuring allowed prirority classes.
Can you try adding your priority class name in this block https://github.com/armadaproject/armada/blob/master/config/armada/config.yaml#L28-L32?

Example:
```
submission:
  allowedPriorityClassNames:
    armada-default: true
    armada-preemptible: true
    armada-resilient: true
    armada-high: true
```
