### ISSUE TITLE
Accessing Armada Pods externally

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada-operator#99]
There are a few different methods for doing this:

# Port Forwarding

This is the simplest method, forwarding the service port to a target port on `0.0.0.0`

```bash
kubectl port-forward service/lookout-sample --address 0.0.0.0 8080:8080
```

# NodePorts

This exposes the service automatically on a port. Nodeports need to be in the range `30000-32767`

## Setup

Any ports that you want to use need to be included in the kind config

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP

    # Any Other Ports
  - containerPort: 30051
    hostPort: 30051
    protocol: TCP
```

The service type then needs to be set to `NodePort` in https://github.com/armadaproject/armada-operator/blob/main/controllers/builders/service.go

```go
	// Create the above but with type "NodePort"
	service = corev1.Service{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace, Labels: labels},
		Spec: corev1.ServiceSpec{
			Selector: identityLabel,
			Ports:    ports,
			Type:     corev1.ServiceTypeNodePort,
		},
	}
```

Then, you can optionally specify the nodeports in https://github.com/armadaproject/armada-operator/blob/main/controllers/install/

```go
	service := builders.Service(as.Name, as.Namespace, AllLabels(as.Name, as.Labels), IdentityLabel(as.Name), []corev1.ServicePort{
		{
			Name:     "grpc",
			Port:     50051,
			NodePort: 30051,
		},
		{
			Name:     "rest",
			Port:     8080,
			NodePort: 30080,
		},
		{
			Name:     "metrics",
			Port:     9000,
			NodePort: 30900,
		},
	})
```

**NOTE: If they are not directly assigned they will be randomly picked from the valid range**

Typing in `kubectl get services -n armada` should then show the services as nodeports with their ports

# Ingress

This is the solution for production. If you want to test locally, you will need to add hostnames to `/etc/hosts`. See https://techhub.hpe.com/eginfolib/networking/docs/IMC/v7_3/5200-2694/content/466972523.htm

Otherwise, you can points your domains towards the ingress-cluster and it should behave as expected.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/AR-148) by [Unito](https://www.unito.io)
